Na wykładzie poznaliśmy parę najważniejszych operacji macierzowych oraz po krótce wyjaśniliśmy, dlaczego są one ważne w uczeniu maszynowym (a nawet kluczowe, kiedy myślimy o złożoności obliczeniowej).

Poniższe ćwiczenia mają na celu zaimplementowanie tych operacji.

In [20]:
import numpy as np

Przydatne do zadań: jak dostać się do konkretnego elementu macierzy? (u nas numpy.array)

In [21]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

a_11 = A[0][0]
a_23 = A[1][2]
a_13 = A[0][2]

print('a_11 =', a_11)
print('a_23 =', a_23)
print('a_13 =', a_13)

a_11 = 1
a_23 = 6
a_13 = 3


Jak dostać się do wymiaru macierzy?

In [22]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.shape) # (liczba rzędów, liczba kolumn)
print(A.shape[0])    # liczba rzędów
print(A.shape[1])    # liczba kolumn


(2, 3)
2
3


# ZADANIE 1

Zaimplementuj dodawnie oraz odejmowanie macierzy, nie korzystając z funkcjonalności biblioteki numpy.

In [23]:
def add_matrix(m1 : np.ndarray, m2 : np.ndarray) -> np.ndarray:
    #TODO
    pass

def subtract_matrix(m1 : np.ndarray, m2 : np.ndarray) -> np.ndarray:
    #TODO
    pass

Test dodawania

In [24]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[-1, 3, 3],
              [-5, 0, 1]])

C = A + B
C_student = add_matrix(A, B)

assert C.shape == C_student.shape
assert (C_student == C).all()
print('Works good!')

AttributeError: 'NoneType' object has no attribute 'shape'

Test odejmowania

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[-1, 3, 3],
              [-5, 0, 1]])

C = A - B
C_student = subtract_matrix(A, B)

assert C.shape == C_student.shape
assert (C_student == C).all()
print('Works good!')

AttributeError: 'NoneType' object has no attribute 'shape'

# Zadanie 2

Zaimplementuj transponens macierzy, nie korzystając z funkcjonalności numpy.

UWAGA! Może zmienić się wymiar macierzy.

In [ ]:
def transpose_matrix(m : np.ndarray) -> np.ndarray:
    #TODO
    pass

Test transpozycji

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

A_t = A.T
B_t = B.T

A_t_student = transpose_matrix(A)
B_t_student = transpose_matrix(B)

assert A_t.shape == A_t_student.shape
assert B_t.shape == B_t_student.shape
assert (A_t == A_t_student).all()
assert (B_t == B_t_student).all()
print('Works good!')

NameError: name 'transpose_matrix' is not defined

# ZADANIE 3

Zaimplementuj mnożenie macierzy, nie korzystając z funkcjonalności numpy.

In [ ]:
def multiply_matrix(m1 : np.ndarray, m2 : np.ndarray) -> np.ndarray:
    #Ta linijka sprawdza, czy podane macierze mają odpowiednie wymiary
    assert m1.shape[1] == m2.shape[0]

    #TODO
    pass

Test mnożenia

In [ ]:
A = np.array([[1, 4],
              [-2, 7],
              [8, 3]])

B = np.array([[3, 6, -4, 0],
              [-1, -9, 3, 2]])

C = np.dot(A, B)
C_student = multiply_matrix(A, B)

assert C.shape == C_student.shape
assert (C == C_student).all()
print('Works good!')

AttributeError: 'NoneType' object has no attribute 'shape'

# ZADANIE 4*

Zaimplementuj odwracanie macierzy. Procedura jest nie łatwa i wymyślenie jej samodzielnie może sprawiać trudność, więc w razie problemów można się posiłkować podanym niżej artykułem (choć zachęcam do zastanowienia!).

https://pl.wikipedia.org/wiki/Metoda_eliminacji_Gaussa

In [ ]:
def inverse_matrix(m : np.ndarray) -> np.ndarray:
    #Ta linijka sprawdza, czy macierz m jest odwracalna
    np.linalg.inv(m)

    #TODO
    pass

Test odwracania

In [ ]:
A = np.array([[7, 2, 1],
              [0, 3, -1],
              [-3, 4, -2]])

print(np.abs(A))

[[7 2 1]
 [0 3 1]
 [3 4 2]]


In [ ]:
A = np.array([[7, 2, 1],
              [0, 3, -1],
              [-3, 4, -2]])

A_inv = np.linalg.inv(A)
A_inv_student = inverse_matrix(A)

assert A_inv.shape == A_inv_student.shape
assert (np.abs(A_inv - A_inv_student) < 0.001).all()
print('Works good!')